sudo: required

language: ruby

services:
  - docker

script:
- cd ./ipse_base && docker build -t supermap/ipse_base:travis .
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- docker push supermap/ipse_base:travis