sudo: required

language: ruby

services:
  - docker

script:
- docker build --tag supermap/iexpress:travis ./iExpress
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- docker push supermap/iexpress:travis