sudo: required

language: ruby

services:
  - docker

script:
- cd ./iExpress && docker build -t supermap/iexpress:travis .
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- docker push supermap/iexpress:travis